apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: sontungbk85/github-jenkins-argocd-k8s:v1
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: web-python
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5001
    nodePort: 32001
  selector:
    app: flask-app